server:
  port: 9999
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.105.197.248:3306/java1907?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  file: c://logs//all.log
# level:
#   root: info

